# values.yaml

# Elasticsearch cluster name
clusterName: "my-elasticsearch-cluster"

# Node configuration
nodeGroup: "master"
masterCount: 1
dataCount: 2
ingestCount: 0

# Resources for the Elasticsearch pods
resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "2000m"
    memory: "2Gi"

# Storage configuration
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: "30Gi"

# Network policies
networkPolicy:
  enabled: false

# Service configuration
service:
  annotations: {}
  type: "ClusterIP"
  port: 9200
  nodePort: ""
  clusterIP: ""

# Node affinity
affinity: {}
